# Generated by Django 3.2.5 on 2022-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0015_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_img',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
