# Generated by Django 3.2.5 on 2022-02-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0018_auto_20220128_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
