# Generated by Django 3.2.5 on 2022-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_add', models.CharField(max_length=250)),
                ('user_phone', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
    ]
