# Generated by Django 3.0.2 on 2022-01-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_phone',
        ),
    ]
