# Generated by Django 3.2.5 on 2022-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20220203_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_somthing',
            field=models.CharField(default='', max_length=1),
        ),
    ]
