# Generated by Django 3.2.5 on 2022-01-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
