# Generated by Django 3.2.5 on 2022-02-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
