# Generated by Django 2.2.5 on 2022-01-26 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('user_addr', models.CharField(max_length=250)),
                ('user_phone', models.CharField(max_length=15)),
                ('profile_img', models.FileField(blank=True, upload_to='')),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('store_addr', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('time', models.TextField()),
                ('store_img', models.ImageField(blank=True, upload_to='static')),
                ('intro', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('c_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.Category')),
            ],
        ),
    ]
