# Generated by Django 3.2.5 on 2022-01-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_addr', models.CharField(max_length=250)),
                ('store_phone', models.CharField(max_length=11)),
                ('time', models.TextField()),
                ('store_img', models.ImageField(blank=True, upload_to='')),
                ('intro', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('eamil', models.CharField(max_length=100)),
                ('user_addr', models.CharField(max_length=250)),
                ('user_phone', models.CharField(max_length=11)),
                ('profile_img', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
