# Generated by Django 3.1.3 on 2022-01-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
    ]
