# Generated by Django 3.1.3 on 2022-01-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
